# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 简介
    url: /
    weight: 10
  - name: 研究方向
    url: /#research
    weight: 11
  - name: 科研项目
    url: /projects/
    weight: 20
  - name: 论文成果
    url: /publications/
    weight: 30
  - name: 教学课程
    url: /courses/
    weight: 40
  - name: 个人经历
    url: experience/
    weight: 50
